# Generated by Django 2.2 on 2019-04-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(default='Ram', max_length=250)),
                ('cust_address', models.TextField(default='JayaNagar Bangalore', max_length=400)),
                ('cust_dept', models.CharField(default='Sales', max_length=250)),
            ],
        ),
    ]
